### ISSUE TITLE
tis kut

### ISSUE THREAD

**Issue by Gijser** [job26a/tickets#1]
moet iets, srry voor aanstootgevende taal :(

**Comment by job26a** [comment]
hoer

**Comment by Gijser** [comment]
you dare oppose me

**Comment by job26a** [comment]
yes

**Comment by Gijser** [comment]
i can see no god up here but ME

**Comment by job26a** [comment]
als jij zo biggie bent kom dan vechten

**Comment by Gijser** [comment]
bold words for someone in crusading range

**Comment by job26a** [comment]
3 bij de parkeerplaats van de api

**Comment by Gijser** [comment]
ben dan al weg, naar je huis

**Comment by Gijser** [comment]
oef

**Comment by Gijser** [comment]
closed
